name: Build and Deploy
on:
  push:
    branches:
    - master
jobs:
  main:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Build Hugo
      uses: lowply/build-hugo@v0.0.2
    - name: Deploy to Firebase
      uses: lowply/deploy-firebase@v0.0.2
      env:
        FIREBASE_TOKEN: 1//0g7C4pJxl70h_CgYIARAAGBASNwF-L9IrDJH8-N52fJa56-T6221xv3KhvKQQ1tSyTJ91t479mtvKcIfpXXkOp7uSBqjFDAImiyY
        FIREBASE_PROJECT: CookPad